set -g __fish_initialized 3400
set -g fish_color_autosuggestion 6272a4
set -g fish_color_cancel ff5555\x1e\x2d\x2dreverse
set -g fish_color_command 8be9fd
set -g fish_color_comment 6272a4
set -g fish_color_cwd 50fa7b
set -g fish_color_cwd_root red
set -g fish_color_end ffb86c
set -g fish_color_error ff5555
set -g fish_color_escape ff79c6
set -g fish_color_history_current \x2d\x2dbold
set -g fish_color_host bd93f9
set -g fish_color_host_remote \x1d
set -g fish_color_keyword \x1d
set -g fish_color_match \x2d\x2dbackground\x3dbrblue
set -g fish_color_normal f8f8f2
set -g fish_color_operator 50fa7b
set -g fish_color_option \x1d
set -g fish_color_param bd93f9
set -g fish_color_quote f1fa8c
set -g fish_color_redirection f8f8f2
set -g fish_color_search_match \x2d\x2dbackground\x3d44475a
set -g fish_color_selection \x2d\x2dbackground\x3d44475a
set -g fish_color_status red
set -g fish_color_user 8be9fd
set -g fish_color_valid_path \x2d\x2dunderline
set -g fish_key_bindings fish_default_key_bindings
set -g fish_pager_color_background \x1d
set -g fish_pager_color_completion f8f8f2
set -g fish_pager_color_description 6272a4
set -g fish_pager_color_prefix 8be9fd
set -g fish_pager_color_progress 6272a4
set -g fish_pager_color_secondary_background \x1d
set -g fish_pager_color_secondary_completion \x1d
set -g fish_pager_color_secondary_description \x1d
set -g fish_pager_color_secondary_prefix \x1d
set -g fish_pager_color_selected_background \x2d\x2dbackground\x3d44475a
set -g fish_pager_color_selected_completion f8f8f2
set -g fish_pager_color_selected_description 6272a4
set -g fish_pager_color_selected_prefix 8be9fd
